Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,24 +1,22 @@
 #!/usr/bin/env bash
-# This script transfers a file from the client to a server using scp.
+# Script transfers files from client to server
+# If less than 3 params transfer to ~/
 
-# Check if the correct number of parameters is provided
-if [ "$#" -ne 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+PATH_TO_FILE="$1";
+IP="$2";
+USERNAME="$3";
+PATH_TO_SSH_KEY="$4";
+ERROR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
+HOST_KEY_RULE="StrictHostKeyChecking=no"
+
+if [ "$#" -lt 3 ]; then
+	echo -e "$ERROR";
+	exit 1;
 fi
 
-# Extract parameters
-path_to_file=$1
-ip=$2
-username=$3
-ssh_key=$4
-
-# Transfer the file to the user's home directory on the server
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip":~/ 
-
-# Check if the scp command was successful
-if [ $? -eq 0 ]; then
-    echo "File transfer successful!"
-else
-    echo "File transfer failed!"
+if [ "$#" -eq 3 ]; then
+	scp -o "$HOST_KEY_RULE" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
+	exit 0;
 fi
+
+scp -o "$HOST_KEY_RULE" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/";
