Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,22 +1,25 @@
 #!/usr/bin/env bash
-# Script transfers files from client to server
-# If less than 3 params transfer to ~/
 
-PATH_TO_FILE="$1";
-IP="$2";
-USERNAME="$3";
-PATH_TO_SSH_KEY="$4";
-ERROR="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
-HOST_KEY_RULE="StrictHostKeyChecking=no"
+# Script to transfer a file from client to server using scp
 
-if [ "$#" -lt 3 ]; then
-	echo -e "$ERROR";
-	exit 1;
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-if [ "$#" -eq 3 ]; then
-	scp -o "$HOST_KEY_RULE" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
-	exit 0;
-fi
+# Assign parameters to variables
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
 
-scp -o "$HOST_KEY_RULE" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/";
+# Use scp to transfer the file to the user's home directory on the server
+scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
+
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File transfer successful."
+else
+    echo "Error transferring file."
+fi
